# Generated by Django 2.2 on 2021-08-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
